export const ACTION_EAT = "ACTION_EAT";
export const ACTION_NAP = "ACTION_NAP";
export const ACTION_PLAY = "ACTION_PLAY";
export const ACTION_SET_NAME = "ACTION_SET_NAME";
export const ACTION_SET_ACTIVITY = "ACTION_SET_ACTIVITY";
export const ACTION_ADD_CAT = "ACTION_ADD_CAT";